title: MattErickson (ME)
email: matt@matterickson.me
description: A personal and professional blog about software, beer, the world, and so much more.
baseurl: ""
url: "http://matterickson.com"
repository: "Mutmatt/mutmatt.github.io"

#analytics
google_analytics: 'UA-38520661-2'
  
# social
twitter_username: MutMatt
github_username: MutMatt
linkedin_username: matthewerickson
twitter:
  username: MutMatt

# google_play: ''
# google_plus_com: ''      # Community link
# google_plus_per: ''      # Personal link
# facebook_app_id: 12345

# Layout settings
header_type: drawer       # values [ drawer, default ]
post_type: highlight        # values [ highlight, default ]
pagination_type: ops      # values [ ops, default ]


disqus: true
disqus_shortname: 'MutMatt'

# Build settings
markdown: kramdown

# gems
gems:
  - jekyll-seo-tag